### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by neeraj395** [Neeraj-error/SNAKE-GAME#1]
### TASKS TO BE DONE 

- [x] FIX THE SNAKE IMAGE AND APPLE IMAGE DISPLAY
- [x] FIX THE BACKGORUND SOUND ISSUE 
- [x] FIX TEH CRUNCH SOUND PLAY ISSUE

**Comment by neeraj395** [comment]
*ERROR FIX UNDER PROGRESS*



NEERAJ
>
